// Auto-generated by generate-image-index.js
// Last generated: 2026-04-22T05:24:43.244Z

import type { FC, SVGProps } from 'react';
import Appstore from './appstore.svg';
import Docker from './docker.svg';
import Dp from './dp.png';
import Expo from './expo.svg';
import Fastlane from './fastlane.svg';
import Figma from './figma.svg';
import Firebase from './firebase.svg';
import Flutter from './flutter.svg';
import Github from './github.svg';
import Laravel from './laravel.svg';
import Nodejs from './nodejs.svg';
import OnCall from './on-call.png';
import Pgsql from './pgsql.svg';
import Playstore from './playstore.svg';
import Postman from './postman.svg';
import React from './react.svg';
import Sibs from './sibs.svg';
import Singlife from './singlife.png';
import Supabase from './supabase.svg';
import Ts from './ts.svg';
import Visitmalta from './visitmalta.png';
import YayaAndDriver from './yaya-and-driver.png';

export {
  Appstore,
  Docker,
  Dp,
  Expo,
  Fastlane,
  Figma,
  Firebase,
  Flutter,
  Github,
  Laravel,
  Nodejs,
  OnCall,
  Pgsql,
  Playstore,
  Postman,
  React,
  Sibs,
  Singlife,
  Supabase,
  Ts,
  Visitmalta,
  YayaAndDriver,
};

// TypeScript exports for better type safety
export type ImageAssets = {
  Appstore: string | React.FC<React.SVGProps<SVGSVGElement>>;
  Docker: string | React.FC<React.SVGProps<SVGSVGElement>>;
  Dp: string;
  Expo: string | React.FC<React.SVGProps<SVGSVGElement>>;
  Fastlane: string | React.FC<React.SVGProps<SVGSVGElement>>;
  Figma: string | React.FC<React.SVGProps<SVGSVGElement>>;
  Firebase: string | React.FC<React.SVGProps<SVGSVGElement>>;
  Flutter: string | React.FC<React.SVGProps<SVGSVGElement>>;
  Github: string | React.FC<React.SVGProps<SVGSVGElement>>;
  Laravel: string | React.FC<React.SVGProps<SVGSVGElement>>;
  Nodejs: string | React.FC<React.SVGProps<SVGSVGElement>>;
  OnCall: string;
  Pgsql: string | React.FC<React.SVGProps<SVGSVGElement>>;
  Playstore: string | React.FC<React.SVGProps<SVGSVGElement>>;
  Postman: string | React.FC<React.SVGProps<SVGSVGElement>>;
  React: string | React.FC<React.SVGProps<SVGSVGElement>>;
  Sibs: string | React.FC<React.SVGProps<SVGSVGElement>>;
  Singlife: string;
  Supabase: string | React.FC<React.SVGProps<SVGSVGElement>>;
  Ts: string | React.FC<React.SVGProps<SVGSVGElement>>;
  Visitmalta: string;
  YayaAndDriver: string;
};

// Helper function to get asset by name
export function getAsset(name: string): string | FC<SVGProps<SVGSVGElement>> {
  const assets: Record<string, string | FC<SVGProps<SVGSVGElement>>> = {
    appstore: Appstore,
    docker: Docker,
    dp: Dp,
    expo: Expo,
    fastlane: Fastlane,
    figma: Figma,
    firebase: Firebase,
    flutter: Flutter,
    github: Github,
    laravel: Laravel,
    nodejs: Nodejs,
    'on-call': OnCall,
    pgsql: Pgsql,
    playstore: Playstore,
    postman: Postman,
    react: React,
    sibs: Sibs,
    singlife: Singlife,
    supabase: Supabase,
    ts: Ts,
    visitmalta: Visitmalta,
    'yaya-and-driver': YayaAndDriver,
  };

  return assets[name.toLowerCase()];
}

// Utility function to get all asset names
export function getAllAssetNames(): string[] {
  return [
    'appstore',
    'docker',
    'dp',
    'expo',
    'fastlane',
    'figma',
    'firebase',
    'flutter',
    'github',
    'laravel',
    'nodejs',
    'on-call',
    'pgsql',
    'playstore',
    'postman',
    'react',
    'sibs',
    'singlife',
    'supabase',
    'ts',
    'visitmalta',
    'yaya-and-driver',
  ];
}
