// Auto-generated by generate-image-index.js
// Last generated: 2025-12-15T09:53:26.759Z

import type { FC, SVGProps } from 'react';
import Appstore from './appstore.svg';
import Docker from './docker.svg';
import Dp from './dp.png';
import Fastlane from './fastlane.svg';
import Figma from './figma.svg';
import Flutter from './flutter.svg';
import Github from './github.svg';
import Laravel from './laravel.svg';
import Nodejs from './nodejs.svg';
import OnCall from './on-call.png';
import Pgsql from './pgsql.svg';
import Playstore from './playstore.svg';
import React from './react.svg';
import Sibs from './sibs.svg';
import Singlife from './singlife.png';
import Ts from './ts.svg';
import YayaAndDriver from './yaya-and-driver.png';

export {
  Appstore,
  Docker,
  Dp,
  Fastlane,
  Figma,
  Flutter,
  Github,
  Laravel,
  Nodejs,
  OnCall,
  Pgsql,
  Playstore,
  React,
  Sibs,
  Singlife,
  Ts,
  YayaAndDriver,
};

// TypeScript exports for better type safety
export type ImageAssets = {
  Appstore: string | React.FC<React.SVGProps<SVGSVGElement>>;
  Docker: string | React.FC<React.SVGProps<SVGSVGElement>>;
  Dp: string;
  Fastlane: string | React.FC<React.SVGProps<SVGSVGElement>>;
  Figma: string | React.FC<React.SVGProps<SVGSVGElement>>;
  Flutter: string | React.FC<React.SVGProps<SVGSVGElement>>;
  Github: string | React.FC<React.SVGProps<SVGSVGElement>>;
  Laravel: string | React.FC<React.SVGProps<SVGSVGElement>>;
  Nodejs: string | React.FC<React.SVGProps<SVGSVGElement>>;
  OnCall: string;
  Pgsql: string | React.FC<React.SVGProps<SVGSVGElement>>;
  Playstore: string | React.FC<React.SVGProps<SVGSVGElement>>;
  React: string | React.FC<React.SVGProps<SVGSVGElement>>;
  Sibs: string | React.FC<React.SVGProps<SVGSVGElement>>;
  Singlife: string;
  Ts: string | React.FC<React.SVGProps<SVGSVGElement>>;
  YayaAndDriver: string;
};

// Helper function to get asset by name
export function getAsset(name: string): string | FC<SVGProps<SVGSVGElement>> {
  const assets: Record<string, string | FC<SVGProps<SVGSVGElement>>> = {
    appstore: Appstore,
    docker: Docker,
    dp: Dp,
    fastlane: Fastlane,
    figma: Figma,
    flutter: Flutter,
    github: Github,
    laravel: Laravel,
    nodejs: Nodejs,
    'on-call': OnCall,
    pgsql: Pgsql,
    playstore: Playstore,
    react: React,
    sibs: Sibs,
    singlife: Singlife,
    ts: Ts,
    'yaya-and-driver': YayaAndDriver,
  };

  return assets[name.toLowerCase()];
}

// Utility function to get all asset names
export function getAllAssetNames(): string[] {
  return [
    'appstore',
    'docker',
    'dp',
    'fastlane',
    'figma',
    'flutter',
    'github',
    'laravel',
    'nodejs',
    'on-call',
    'pgsql',
    'playstore',
    'react',
    'sibs',
    'singlife',
    'ts',
    'yaya-and-driver',
  ];
}
